# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: final
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    
  db:
    image: postgres:15.7
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=arely
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  db-data:
